Cargo fmt and other misc updates
Kixunil/loptos pull request #10
Opened 2022-07-24 19:19 UTC by 0xBEEFCAF3

Got a working example using Wasabi. In the process of getting everything set up, I updated some docs, updated some dependency versions, gitignore, and setup a template config file. Hope others will find this useful

2022-07-24 22:12 UTC, Kixunil requested changes
Thanks for the PR and reporting success with Wasabi! There are some good ideas. Unfortunately you made some mistakes and I hate `rustfmt` formatting. Please avoid reformatting the code, I will try to configure rustfmt to produce something nicer later. I pointed out things I dislike so you could try it too but I'd prefer to do it later, in a separate PR.

Also, very important, never mix formatting commits with anything else. It makes it painful to review and it is probably no-go in other projects as well.

2022-07-24 22:12 UTC, Kixunil commented on src/main.rs
> +                }
Missing commas are confusing.

2022-07-24 22:12 UTC, Kixunil commented on src/main.rs
> +        );
Amount string needs to go to a variable to not blow up the call. (Also ideally we would bump `bitcoin` version once it's realeased and use the newly added `display_in` method.)

2022-07-24 22:12 UTC, Kixunil commented on conf_dir/conf.template
> +lnd_address = "tcp://localhost:10009"
I will have to study what `tcp:` does, probably unsecure connection. Please use https instead or explain why you used `tcp`

2022-08-08 06:54 UTC, DanGould commented on Cargo.toml
> +ln-types = { version = "0.1.3", features = ["serde", "parse_arg"] }
Yes that has been my experience

2022-08-08 06:56 UTC, DanGould commented on .gitignore
> +**/*.rs.backup
second, I'm not sure what this is even after trying to duplicate

2022-08-08 06:56 UTC, DanGould commented on README.md
> +0. Copy `conf_dir/conf.template` to `conf_dir/conf` and replace values
afaik there's no man page that shows that yet

2022-08-08 06:57 UTC, DanGould commented on src/main.rs
> +const STATIC_DIR: &str = "static";
agree. compile with `cargo build --features=test_paths`. use the feature as intended

2022-08-08 06:58 UTC, DanGould commented on src/main.rs
> +        Config::including_optional_config_files(&["conf_dir/conf"]).unwrap_or_exit();
seems like there's no man page which would help find this piece of docs

2022-08-08 12:42 UTC, closed without merging